import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import Navbar from "./components/common/Navbar";
import Footer from "./components/common/Footer";
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      style={{ scrollBehavior: "smooth" }}
      className="scroll-smooth"
      lang="en"
    >
      <body className={`${spaceGrotesk.variable} ${inter.className}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
